#ifndef _COLOR565_H__
#define _COLOR565_H__

#define ALICE_BLUE                 0xF7DF
#define ANTIQUE_WHITE              0xFF5A
#define AQUA                       0x07FF
#define AQUAMARINE                 0x7FFA
#define AZURE                      0xF7FF
#define BEIGE                      0xF7BB
#define BISQUE                     0xFF38
#define BLACK                      0x0000
#define BLANCHED_ALMOND            0xFF59
#define BLUE                       0x001F
#define BLUE_VIOLET                0x895C
#define BROWN                      0xA145
#define BURLY_WOOD                 0xDDD0
#define CADET_BLUE                 0x5CF4
#define CHARTREUSE                 0x7FE0
#define CHOCOLATE                  0xD343
#define CORAL                      0xFBEA
#define CORNFLOWER_BLUE            0x64BD
#define CORNSILK                   0xFFDB
#define CRIMSON                    0xD8A7
#define CYAN                       0x07FF
#define DARK_BLUE                  0x0011
#define DARK_CYAN                  0x0451
#define DARK_GOLDEN_ROD            0xBC21
#define DARK_GRAY                  0xAD55
#define DARK_GREEN                 0x0320
#define DARK_KHAKI                 0xBDAD
#define DARK_MAGENTA               0x8811
#define DARK_OLIVE_GREEN           0x5345
#define DARK_ORANGE                0xFC60
#define DARK_ORCHID                0x9999
#define DARK_RED                   0x8800
#define DARK_SALMON                0xECAF
#define DARK_SEA_GREEN             0x8DF1
#define DARK_SLATE_BLUE            0x49F1
#define DARK_SLATE_GRAY            0x2A69
#define DARK_TURQUOISE             0x067A
#define DARK_VIOLET                0x901A
#define DEEP_PINK                  0xF8B2
#define DEEP_SKY_BLUE              0x05FF
#define DIM_GRAY                   0x6B4D
#define DODGER_BLUE                0x1C9F
#define FIRE_BRICK                 0xB104
#define FLORAL_WHITE               0xFFDE
#define FOREST_GREEN               0x2444
#define FUCHSIA                    0xF81F
#define GAINSBORO                  0xDEFB
#define GHOST_WHITE                0xFFDF
#define GOLD                       0xFEA0
#define GOLDEN_ROD                 0xDD24
#define GRAY                       0x8410
#define GREEN                      0x0400
#define GREEN_YELLOW               0xAFE5
#define HONEY_DEW                  0xF7FE
#define HOT_PINK                   0xFB56
#define INDIAN_RED                 0xCAEB
#define INDIGO                     0x4810
#define IVORY                      0xFFFE
#define KHAKI                      0xF731
#define LAVENDER                   0xE73F
#define LAVENDER_BLUSH             0xFF9E
#define LAWN_GREEN                 0x7FE0
#define LEMON_CHIFFON              0xFFD9
#define LIGHT_BLUE                 0xAEDC
#define LIGHT_CORAL                0xF410
#define LIGHT_CYAN                 0xE7FF
#define LIGHT_GOLDEN_ROD_YELLOW    0xFFDA
#define LIGHT_GRAY                 0xD69A
#define LIGHT_GREEN                0x9772
#define LIGHT_PINK                 0xFDB8
#define LIGHT_SALMON               0xFD0F
#define LIGHT_SEA_GREEN            0x2595
#define LIGHT_SKY_BLUE             0x867F
#define LIGHT_SLATE_GRAY           0x7453
#define LIGHT_STEEL_BLUE           0xB63B
#define LIGHT_YELLOW               0xFFFC
#define LIME                       0x07E0
#define LIME_GREEN                 0x3666
#define LINEN                      0xFF9C
#define MAGENTA                    0xF81F
#define MAROON                     0x8000
#define MEDIUM_AQUA_MARINE         0x6675
#define MEDIUM_BLUE                0x0019
#define MEDIUM_ORCHID              0xBABA
#define MEDIUM_PURPLE              0x939B
#define MEDIUM_SEA_GREEN           0x3D8E
#define MEDIUM_SLATE_BLUE          0x7B5D
#define MEDIUM_SPRING_GREEN        0x07D3
#define MEDIUM_TURQUOISE           0x4E99
#define MEDIUM_VIOLET_RED          0xC0B0
#define MIDNIGHT_BLUE              0x18CE
#define MINT_CREAM                 0xF7FF
#define MISTY_ROSE                 0xFF3C
#define MOCCASIN                   0xFF36
#define NAVAJO_WHITE               0xFEF5
#define NAVY                       0x0010
#define OLD_LACE                   0xFFBC
#define OLIVE                      0x8400
#define OLIVE_DRAB                 0x6C64
#define ORANGE                     0xFD20
#define ORANGE_RED                 0xFA20
#define ORCHID                     0xDB9A
#define PALE_GOLDEN_ROD            0xEF55
#define PALE_GREEN                 0x9FD3
#define PALE_TURQUOISE             0xAF7D
#define PALE_VIOLET_RED            0xDB92
#define PAPAYA_WHIP                0xFF7A
#define PEACH_PUFF                 0xFED7
#define PERU                       0xCC27
#define PINK                       0xFE19
#define PLUM                       0xDD1B
#define POWDER_BLUE                0xB71C
#define PURPLE                     0x8010
#define RED                        0xF800
#define ROSY_BROWN                 0xBC71
#define ROYAL_BLUE                 0x435C
#define SADDLE_BROWN               0x8A22
#define SALMON                     0xFC0E
#define SANDY_BROWN                0xF52C
#define SEA_GREEN                  0x2C4A
#define SEA_SHELL                  0xFFBD
#define SIENNA                     0xA285
#define SILVER                     0xC618
#define SKY_BLUE                   0x867D
#define SLATE_BLUE                 0x6AD9
#define SLATE_GRAY                 0x7412
#define SNOW                       0xFFDF
#define SPRING_GREEN               0x07EF
#define STEEL_BLUE                 0x4416
#define TAN                        0xD5B1
#define TEAL                       0x0410
#define THISTLE                    0xDDFB
#define TOMATO                     0xFB08
#define TURQUOISE                  0x471A
#define VIOLET                     0xEC1D
#define WHEAT                      0xF6F6
#define WHITE                      0xFFFF
#define WHITE_SMOKE                0xF7BE
#define YELLOW                     0xFFE0
#define YELLOW_GREEN               0x9E66

#endif
